name: devops-notes-manager CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Say hello from CI
        run: echo "Hello from GitHub Actions CI"

      - name: list repo files
        run: ls -la

      - name: Build Docker image
        run: docker compose build

      - name: start docker containers
        run: docker compose up -d

      - name: list docker containers
        run: docker ps -a

      - name: wait for services to be ready
        run: sleep 15
      - name: Show container logs
        run: docker compose logs

      - name: Check flask app is running
        run: curl -f http://localhost:5000/ || exit 1

      - name: stop docker containers
        if: always()
        run: docker compose down
